apiURL: "https://api.bw6.com/"
tradeRUL: "https://trade.bw6.com/"
klineURL: "wss://kline.bw6.com/websocket"
wsapiURL: "wss://api.bw6.com/websocket"
interval: 3s # 下单时间间隔

markets:
  - trxusdt
  - btcusdt
#  - trxbtc

accounts:
  - name: "c7t46gox2o@eurokool.com" # id: 11
    accessKey: "d1308183-a809-4930-b5a2-c946b8ca327a"
    secretKey: "252fa87e-09a5-4f95-b2f6-af0b4d472666"
  - name: "kjhnh5n1wc@eurokool.com" # id: 12
    accessKey: "92379a60-b81e-483a-866f-1f8061e38169"
    secretKey: "21f80cdc-5b7b-496d-9c36-c68d39dba72e"
